apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment-green
  labels: 
    tier: application 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: __REGISTRY-LOGIN-SERVER__/nginx-green:1
        ports: 
        - containerPort: 80

